/*  =========================================================================
    exo-nico - generated layer of public API

    Copyright (C) 2014 - 2017 Eaton                                        
                                                                           
    This program is free software; you can redistribute it and/or modify   
    it under the terms of the GNU General Public License as published by   
    the Free Software Foundation; either version 2 of the License, or      
    (at your option) any later version.                                    
                                                                           
    This program is distributed in the hope that it will be useful,        
    but WITHOUT ANY WARRANTY; without even the implied warranty of         
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          
    GNU General Public License for more details.                           
                                                                           
    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.            

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef EXO_NICO_LIBRARY_H_INCLUDED
#define EXO_NICO_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>
#include <malamute.h>

//  EXO_NICO version macros for compile-time API detection
#define EXO_NICO_VERSION_MAJOR 1
#define EXO_NICO_VERSION_MINOR 0
#define EXO_NICO_VERSION_PATCH 0

#define EXO_NICO_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define EXO_NICO_VERSION \
    EXO_NICO_MAKE_VERSION(EXO_NICO_VERSION_MAJOR, EXO_NICO_VERSION_MINOR, EXO_NICO_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined EXO_NICO_STATIC
#       define EXO_NICO_EXPORT
#   elif defined EXO_NICO_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define EXO_NICO_EXPORT __declspec(dllexport)
#       else
#           define EXO_NICO_EXPORT
#       endif
#   elif defined EXO_NICO_EXPORTS
#       define EXO_NICO_EXPORT __declspec(dllexport)
#   else
#       define EXO_NICO_EXPORT __declspec(dllimport)
#   endif
#   define EXO_NICO_PRIVATE
#else
#   define EXO_NICO_EXPORT
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define EXO_NICO_PRIVATE __attribute__ ((visibility ("hidden")))
#   else
#       define EXO_NICO_PRIVATE
#   endif
#endif

//  Project has no stable classes, so we build the draft API
#undef  EXO_NICO_BUILD_DRAFT_API
#define EXO_NICO_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
#ifdef EXO_NICO_BUILD_DRAFT_API
typedef struct _exo_nico_server_t exo_nico_server_t;
#define EXO_NICO_SERVER_T_DEFINED
typedef struct _exo_nico_client_t exo_nico_client_t;
#define EXO_NICO_CLIENT_T_DEFINED
#endif // EXO_NICO_BUILD_DRAFT_API


//  Public classes, each with its own header file
#ifdef EXO_NICO_BUILD_DRAFT_API
#include "exo_nico_server.h"
#include "exo_nico_client.h"
#endif // EXO_NICO_BUILD_DRAFT_API

#ifdef EXO_NICO_BUILD_DRAFT_API
//  Self test for private classes
EXO_NICO_EXPORT void
    exo_nico_private_selftest (bool verbose);
#endif // EXO_NICO_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
